# Generated by Django 5.0.3 on 2024-05-22 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Birth_cirtification', models.ImageField(upload_to='offcial_papers/Birth_cirtification/%y/%m/%d')),
                ('Id_Card', models.ImageField(upload_to='offcial_papers/Id_Card_Photo/%y/%m/%d')),
                ('Passport', models.ImageField(upload_to='offcial_papers/Passport_Photo/%y/%m/%d')),
                ('Driving_Licence', models.ImageField(upload_to='offcial_papers/Driving_Licence_Photo/%y/%m/%d')),
            ],
        ),
    ]
