# Generated by Django 5.0.3 on 2024-05-22 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Driving_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_in_Arabic', models.CharField(default=None, max_length=255)),
                ('Name_in_English', models.CharField(max_length=255)),
                ('Full_Address', models.CharField(default=None, max_length=255)),
                ('National_ID', models.CharField(default=None, max_length=15)),
                ('Job', models.CharField(default=None, max_length=255)),
                ('Marital_State', models.CharField(default=None, max_length=255)),
                ('Nationality', models.CharField(choices=[('Egyptian', 'Egyptian')], max_length=255)),
                ('Traffic_Department', models.CharField(default=None, max_length=255)),
                ('Blood_Type', models.CharField(choices=[('A+', 'A Plus'), ('A-', 'A Minus'), ('B+', 'B Plus'), ('B-', 'B Minus'), ('AB+', 'Ab Plus'), ('AB-', 'Ab Minus'), ('O+', 'O Plus'), ('O-', 'O Minus')], max_length=13)),
                ('Medical_Examine_Image', models.ImageField(upload_to='Reniew_Driving_License_Photo/Medical_Examine/%y/%m/%d')),
                ('Request_Date', models.DateField(auto_now=True)),
                ('Receive_Date', models.DateField(default='2024-7-18')),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_ID_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=255)),
                ('Birth_dt', models.DateField()),
                ('Full_Address', models.CharField(default=None, max_length=255)),
                ('National_ID', models.CharField(default=None, max_length=15)),
                ('Current_Job', models.CharField(default=None, max_length=255)),
                ('Marital_State', models.CharField(default=None, max_length=255)),
                ('Study_Field', models.CharField(default=None, max_length=255)),
                ('Recent_Personal_Image', models.ImageField(upload_to='Reniew_ID_Photo/%y/%m/%d')),
                ('Request_Date', models.DateField(auto_now_add=True)),
                ('Receive_Date', models.DateField()),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
