# Generated by Django 5.0.3 on 2024-05-22 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_career',
            fields=[
                ('Sender', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Current_Jop', models.CharField(default=None, max_length=200)),
                ('Campanies', models.TextField()),
                ('Other', models.TextField(default=None)),
            ],
        ),
    ]
