# Generated by Django 5.0.3 on 2024-05-22 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(default=' ', max_length=100)),
                ('Email', models.EmailField(default=' ', max_length=254, unique=True)),
                ('Profession', models.CharField(default=' ', max_length=100)),
                ('Address', models.CharField(default=' ', max_length=100)),
                ('City', models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Aswan', 'Aswan'), ('Alexandria', 'Alexandria'), ('Amarna city', 'Amarna City'), ('Elephantine city', 'Elephantine City'), ('Days cairo tour packages', 'Days Cairo Tour Packages'), ('Damietta', 'Damietta'), ('Luxor', 'Luxor'), ('Heliopolis city', 'Heliopolis City'), ('Qena', 'Qena'), ('Zagazig', 'Zagazig'), ('Fayoum', 'Fayoum'), ('Minya', 'Minya'), ('Al maḩallah al kubrá', 'Al Maḩallah Al Kubrá'), ('Mansoura', 'Mansoura')], default=' ', max_length=100)),
                ('state', models.CharField(choices=[('Egypt', 'Egypt')], default='Egypt', max_length=100)),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
