# Generated by Django 5.0.3 on 2024-05-22 20:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.CharField(default=' ', max_length=11)),
                ('Linkedin_Profile_Link', models.URLField(default='https/', max_length=100, unique=True)),
                ('Twitter_Profile_Link', models.URLField(default='https/', max_length=100, unique=True)),
                ('GitHub_Profile_Link', models.URLField(default='https/', max_length=100, unique=True)),
                ('Portfolio_Link', models.URLField(default='https/', max_length=100, unique=True)),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(default=' ', max_length=100)),
                ('School_Location', models.CharField(default=' ', max_length=100)),
                ('Degree_Program', models.CharField(default=' ', max_length=100)),
                ('Field_Of_Study', models.CharField(default=' ', max_length=100)),
                ('Graduation_Month_and_Year', models.DateField(default=datetime.date(2024, 5, 22), null=True)),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expereince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(default=' ', max_length=100)),
                ('Employer', models.CharField(default=' ', max_length=100)),
                ('Role', models.CharField(default=' ', max_length=100)),
                ('Company_Address', models.CharField(default=' ', max_length=100)),
                ('Start_Date', models.DateField(default=' ')),
                ('Finish_Date', models.DateField(default=' ')),
                ('Currently_work_here', models.BooleanField(default=False)),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill1', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Skill2', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Skill3', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Skill4', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Skill5', models.CharField(choices=[('Html', 'Html'), ('Css', 'Css'), ('Javascript', 'Javascript'), ('React', 'React'), ('Angular', 'Angular'), ('Vue.js', 'Vue'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('Node.js', 'Nodejs'), ('C#', 'C'), ('MongoDB', 'Mongodb'), ('SQL', 'Sql'), ('PostgreSQL', 'Postgresssql'), ('Git', 'Git'), ('Github', 'Github'), ('Power BI', 'Power Bi'), ('UI/UX Designing', 'Uiux'), ('Figma', 'Figma'), ('Adobe XD', 'Xd'), ('Microsoft Excel', 'Excel'), ('Microsoft Word', 'Word'), ('Microsoft Power Point', 'Powerpoint'), ('Content Creator', 'Content Creator'), ('Writing', 'Writing'), ('Translation', 'Translation'), ('Editing', 'Editing'), ('Video Editing', 'Video Editing'), ('Adobe Pr', 'Pr')], max_length=50, unique=True)),
                ('Sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
