# Generated by Django 5.0.3 on 2024-05-22 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page',
            fields=[
                ('User', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.CharField(default=None, max_length=50)),
                ('Nationality', models.CharField(default=None, max_length=100)),
                ('Marital_state', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=9)),
                ('Blood_quarter', models.CharField(choices=[('A+', 'A Plus'), ('A-', 'A Minus'), ('B+', 'B Plus'), ('B-', 'B Minus'), ('AB+', 'Ab Plus'), ('AB-', 'Ab Minus'), ('O+', 'O Plus'), ('O-', 'O Minus')], default=None, max_length=3)),
                ('Address', models.CharField(default=None, max_length=40)),
                ('BirthDate', models.DateField()),
            ],
        ),
    ]
